# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr-ca
  contentDir: content/fr
#  title: Chinese website title...
  params:
#    description: Site description in Chinese...
    directions: Bureau GNN279, au deuxième étage du batiment Gendron
  menu:
    main:
      - name: Contact
        url: 'contact'
        weight: 70
