# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  name = "People"
  url = "people"
  weight = 40

[[main]]
  name = "Projects"
  url = "projects"
  weight = 30

[[main]]
  name = "Courses"
  url = "courses"
  weight = 60

  [[main]]
  name = "uOttawa classes"
  parent = "Courses"
  url = "courses/uottawa"
  weight = 1

  [[main]]
  name = "Tutorials"
  parent = "Courses"
  url = "courses/tutorials"
  weight = 2

[[main]]
  name = "Opportunities"
  url = "opportunities"
  weight = 50

  [[main]]
  name = "Contact"
  url = "contact"
  weight = 70

[[main]]
  name = "Current lab member"
  parent = "People"
  url = "people/people"
  weight = 1

[[main]]
  name = "Alumni"
  parent = "People"
  url = "people/alumni"
  weight = 2

[[main]]
  name = "Visitors"
  parent = "People"
  url = "people/visiting"
  weight = 3

#[[main]]
#  name = "Blog"
#  url = "blog"
#  weight = 80