on:
  push:
    branches:
      - main
      - master

name: blogdown
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.WEBSITE_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

#      - name: Cache Renv packages
#        uses: actions/cache@v3
#        with:
#          path: $HOME/.local/share/renv
#          key: r-${{ hashFiles('renv.lock') }}
#          restore-keys: r-

#      - name: Install hugo
#        run: |
#          brew install hugo

      - name: Install packages
        run: |
          install.packages(c("rmarkdown", "blogdown", "scholar", "tidyverse", "glue"))
#          R -e 'install.packages(c("renv", "rmarkdown", "blogdown"))'
#          R -e 'renv::restore()'
        shell: Rscript {0}

      - name: Build site via blogdown
        run: |
          blogdown::install_hugo(version = "0.92.0", extended = TRUE)
          blogdown::build_site(local = TRUE, build_rmd = 'newfile')
          file.create("public/.nojekyll")
        shell: Rscript {0}


      - name: Install npm
        uses: actions/setup-node@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.WEBSITE_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: public/ # The folder the action should deploy.
          clean: true 
